_target_: lib.models.lightning.bert.NarcissisticPostBERTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-4
  weight_decay: 1e-2

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

hg_bert_model_name: "FacebookAI/xlm-roberta-base"
dropout_rate: 0.1