# @package _global_

defaults:
  - _self_
  - data: narcissistic_posts_lightning
  - model: lightning/bert
  - logger: neptune
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["bert", "eval"]

# passing checkpoint path is necessary for evaluation
# ckpt_path: /Users/janpiotrowski/Projekty/narcissistic-twitter/.neptune/Untitled/TWIT-173/checkpoints/epoch=2-step=18.ckpt
ckpt_path: /home/maciej/Desktop/narcissistic-twitter/.neptune/Untitled/TWIT-509/checkpoints/epoch=3-step=24.ckpt

# data:
#   post_category: post_abortion
#   label_category: adm
#   second_post_category: post_travel
