# @package _global_

defaults:
  - _self_
  - data: narcissistic_posts
  - model: bert
  - logger: neptune
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: # TODO neptune or local link
